### ISSUE TITLE
There was an error in the code

### ISSUE THREAD

**Issue by ma893460966** [NesyaLab/Quantum-Hybrid-Diffusion-Models#2]
While I was debugging main.py ， I got the following error code

Traceback (most recent call last):
  File "/home/lenovo/xiaoma-2023/Quantum-DDPM-2024/Quantum-Hybrid-Diffusion-Models-2024/main.py", line 42, in <module>
    app.run(main)
  File "/home/lenovo/anaconda3/envs/Quantum-State-Learning/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/lenovo/anaconda3/envs/Quantum-State-Learning/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/lenovo/xiaoma-2023/Quantum-DDPM-2024/Quantum-Hybrid-Diffusion-Models-2024/main.py", line 36, in main
    state= train.train(FLAGS.config, FLAGS.workdir)
  File "/home/lenovo/xiaoma-2023/Quantum-DDPM-2024/Quantum-Hybrid-Diffusion-Models-2024/train.py", line 454, in train
    if config.wandb.log_train and jax.process_index() == 0:
  File "/home/lenovo/anaconda3/envs/Quantum-State-Learning/lib/python3.10/site-packages/ml_collections/config_flags/config_flags.py", line 469, in __getattr__
    self._ReportError()
  File "/home/lenovo/anaconda3/envs/Quantum-State-Learning/lib/python3.10/site-packages/ml_collections/config_flags/config_flags.py", line 487, in _ReportError
    raise IOError('Configuration is not available because of an earlier '
OSError: Configuration is not available because of an earlier failure to load: [Errno 21] Is a directory: '/home/lenovo/xiaoma-2023/Quantum-DDPM-2024/Quantum-Hybrid-Diffusion-Models-2024/configs'

This problem arises in    flags. DEFINE_string("workdir", '/home/lenovo/xiaoma-2023/Quantum-DDPM-2024/Quantum-Hybrid-Diffusion-Models-2024/configs', "Work unit directory.")

Can the author tell me how to solve this problem

**Comment by ma893460966** [comment]
I've fixed this
